modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "All Rights Reserved"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "RPG Core"
description = '''
Core systems for the RPG modpack: stats, traits, loot, forging, danger, dungeons, bosses, rifts, towns, quests and homes.
'''

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "tacz"
mandatory = false
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "irons_spellbooks"
mandatory = false
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "curios"
mandatory = false
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"
